### ISSUE TITLE
/dist directory dissapears

### ISSUE THREAD

**Issue by dominiccdj** [USKhokhar/astro-vitae#1]
Hi,
 
I've tried using your template but when running either `npm run build` or `npx astro build` I don't get any output in `dist` directory.  More precisely during build "dist" folder appears and disappears after a second. This is not the case with other basic astro projects where it builds well.

Have you encountered this issue maybe?

BR,
Dominik

**Comment by USKhokhar** [comment]
I just looked into it. And yes, it does create a dist file and then it disappears. 
From what I saw in the logs after running `npm run build`, I think this might be happening because of the `@astrojs/vercel/serverless` package I've used. (I'm attaching the logs so you can also take a look). I'm not much aware of how it works, so I will look at how this astro-vercel integration is working under the hood. 

Instead of the `dist` folder, it is generating a `.vercel` file, so that's another thing too.

<img width="365" alt="image" src="https://github.com/USKhokhar/astro-vitae/assets/63156376/65913bb5-f170-4af3-88de-cbdccc1f4ceb">


Thanks for trying out this template.

< /> 
USK

**Comment by USKhokhar** [comment]
I took a dive into the `.vercel` directory and it does have a `dist` sub-directory. Looks like it can do same stuff :)

<img width="155" alt="image" src="https://github.com/USKhokhar/astro-vitae/assets/63156376/4ccd0937-7a16-4fa8-9273-95f66d27ca99">

**Comment by ulreck-drulk** [comment]
Hi!

I found the exact same issue, i tried using the dist folder inside .vercel but when I deployed it keeps showing a blank page. Any ideas how to work aoround it ?
Thanks
Roger C.

**Comment by ulreck-drulk** [comment]
Eureka!
Pretty simple:
go to your astro.config.mjs
Remove any Vercel-specific configurations including the @astrojs/vercel adapter.
Then we run the builder again:
npm run build

And it creates the missing folder. (Confirmed deployment on cloudfare)

**Comment by bunkerapps** [comment]
I had the same issue and fixed changing the astro.config.mjs like Astro doc's recommend's:
```
export default defineConfig({
  integrations: [tailwind(), alpinejs()],
  output: 'static'
  // adapter: vercel({
  //   analytics: true,
  // }),
});
```
Hope it Helps!

**Comment by bunkerapps** [comment]
Yesterday I set a PR to fix this problem! hope it help's 🚀
[here](https://github.com/USKhokhar/astro-vitae/pull/3#issue-2110944614)

**Comment by USKhokhar** [comment]
Thanks a lot to everyone for contributing to this project, and enhancing it! 🚀
